"""empty message

Revision ID: af5b7c51bea9
Revises: 
Create Date: 2019-07-14 12:13:11.164126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af5b7c51bea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.alter_column('measurments', 'time_stamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measurments', 'time_stamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('users')
    # ### end Alembic commands ###
